### ISSUE TITLE
Error while adding peers

### ISSUE THREAD

**Issue by rnbdev** [getonchain/yudhisthira#8]
While adding a peer node to an admin node, the admin node throws an error.

```
$ ./yudhisthira --add-peer --admin-port 5001 --peer-port 4002
%HTTPotion.Response{
  body: "",
  headers: %HTTPotion.Headers{hdrs: %{"content-length" => "0"}},
  status_code: 500
}
```

```
./yudhisthira run --port 4002

15:47:56.994 [info]  Application starting on http://127.0.0.1:4002

15:47:56.994 [info]  Admin application running on http://127.0.0.1:5002
```

```
$ ./yudhisthira run --port 4001

15:47:55.812 [info]  Application starting on http://127.0.0.1:4001

15:47:55.812 [info]  Admin application running on http://127.0.0.1:5001

15:48:01.928 [info]  Adding peer

15:48:01.965 [error] GenServer #PID<0.418.0> terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:167: :gen_tcp.connect/4
    (ibrowse) /home/ranadeep/projects/yudhisthira/deps/ibrowse/src/ibrowse_http_client.erl:786: :ibrowse_http_client.send_req_1/8
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.416.0>): {:send_req, {{:url, 'http://:4002/authenticate', [], 4002, :undefined, :undefined, '/authenticate', :http, :hostname}, [{'x-yudhisthira-hostname', '127.0.0.1'}, {'x-yudhisthira-host-port', '4001'}], :get, "", [], 5000}}
State: {:state, [], 4002, :undefined, #Reference<0.2830723986.465829890.10984>, false, :undefined, [], false, :undefined, false, [], {[], []}, :undefined, :idle, :undefined, "", 0, 0, [], :undefined, :undefined, :undefined, :undefined, false, :undefined, :undefined, "", :undefined, false, #Reference<0.2830723986.465960962.10978>, 0, :undefined, :undefined}
Client #PID<0.416.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:219: :gen_server.call/3
    (ibrowse) /home/ranadeep/projects/yudhisthira/deps/ibrowse/src/ibrowse_http_client.erl:113: :ibrowse_http_client.send_req/7
    (ibrowse) /home/ranadeep/projects/yudhisthira/deps/ibrowse/src/ibrowse.erl:491: :ibrowse.do_send_req/7
    (ibrowse) /home/ranadeep/projects/yudhisthira/deps/ibrowse/src/ibrowse.erl:383: :ibrowse.try_routing_request/14
    (httpotion) lib/httpotion.ex:453: HTTPotion.request/3
    (yudhisthira) lib/authentication_client.ex:44: Yudhisthira.AuthenticationClient.authenticate/3
    (yudhisthira) lib/controllers/admin_controller.ex:28: Yudhisthira.Controllers.AdminController.add_peer/1

15:48:01.970 [error] #PID<0.416.0> running Yudhisthira.Plugs.AdminHttp (connection #PID<0.415.0>, stream id 1) terminated
Server: 127.0.0.1:5001 (http)
Request: POST /admin/peers
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: false
        (yudhisthira) lib/authentication_client.ex:52: Yudhisthira.AuthenticationClient.authenticate_smp/4
        (yudhisthira) lib/controllers/admin_controller.ex:28: Yudhisthira.Controllers.AdminController.add_peer/1
        (yudhisthira) lib/plugs/admin_http.ex:1: Yudhisthira.Plugs.AdminHttp.plug_builder_call/2
        (plug_cowboy) lib/plug/cowboy/handler.ex:12: Plug.Cowboy.Handler.init/2
        (cowboy) /home/ranadeep/projects/yudhisthira/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /home/ranadeep/projects/yudhisthira/deps/cowboy/src/cowboy_stream_h.erl:293: :cowboy_stream_h.execute/3
        (cowboy) /home/ranadeep/projects/yudhisthira/deps/cowboy/src/cowboy_stream_h.erl:271: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Even the admin node returns an empty peer list after this.

```
./yudhisthira --list-peers --admin-port 5001
[]
```

**Comment by arijitdasgupta** [comment]
Is there any chance this there was a change in the `config.exs`? Looks like it's sending a request to `http://:4002/authenticate`? 

By default the hostname should be `127.0.0.1`, from the config unless overridden from the command line.

**Comment by rnbdev** [comment]
`config/config.exs` is same as in [latest commit](https://github.com/getonchain/yudhisthira/blob/1aced48748e23b0d7efb3f4091d1871c9ce555e4/config/config.exs) in master branch.

**Comment by arijitdasgupta** [comment]
Interesting. I will take a look. Elixir version 1.7?

**Comment by arijitdasgupta** [comment]
Has this been resolved?

**Comment by narendrakpatel** [comment]
@arijitdasgupta  No, this issue has not been solved yet. I compiled the master branch with `Elixir 1.8.0 (compiled with Erlang/OTP 21)`. Also, can you tell me how I can test on the develop branch? I wanted to check if the same issue arises on that branch.

**Comment by arijitdasgupta** [comment]
@narendrakpatel thanks. I will take a look.

**Comment by arijitdasgupta** [comment]
@narendrakpatel @rnbdev Fixed the issue on `develop`.

Please follow the README on `develop`.

A default was missing for the CLI scripts. Should work fine now. Thanks! Apologies, took so long, while reproducing, I wasn't following the README properly.

**Comment by arijitdasgupta** [comment]
I will create a PR with the right README on `master`.

**Comment by arijitdasgupta** [comment]
PR https://github.com/getonchain/yudhisthira/pull/10 should fix it.

**Comment by RatulSaha** [comment]
@narendrakpatel thank for you for the contribution, feel free to dig in, we need more hands and eyes on the code!
